name: Suggestion
description: Suggest a feature.
title: "[Suggestion]: "
labels: ["Suggestion"]
projects: ["BloxerExists/dm-bot"]
assignees:
  - BloxerExists
body:
  - type: markdown
    attributes:
      label: READ THIS BEFORE OPENING A REQUEST
      value: |
        You will be blocked from opening further requests if you don't follow these rules.

        Before opening a request, make sure a similar request doesn't already exist by searching the existing issues.

        If a similar request already exists, DO NOT reply something like "i want this as well". Instead, react with 👍. Only reply if you want to add additional info.
  - type: markdown
    attributes:
       label: One Request per issue
       value: |
        Do not include multiple requests in one issue. If you are making 5 requests, make 5 separate issues
  - type: textarea
    id: info
    attributes:
      label: Give us more info about your suggestion!
      description: Please be as detailed as possible!
      placeholder: ex. I want featuer XY!
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thanks for helping to improve the bot! 💜
  - type: checkboxes
    id: terms
    attributes:
      label: I confirm that this Suggestion is in fact unique!
      description: By submitting this suggestion you confirm that this isnt a duplicate
    validations:
      required: true
